export {HeroSection} from "@/components/root/HomePage/HeroSection"
export {Ventajas} from "@/components/root/HomePage/Ventajas"
export {Objetivo} from "@/components/root/HomePage/Objetivo"
export {Numeralia} from "@/components/root/HomePage/Numeralia"
export {Map} from "@/components/root/HomePage/Map"
export {Noticias} from "@/components/root/HomePage/Noticias"
export {Footer} from "@/components/root/HomePage/Footer"
export {Services} from "@/components/root/HomePage/Services"
